package domain

// Prompts of the AI flow (CR-039). "Chạy bằng AI" no longer asks a model for
// the whole artefact in one turn, so it does not use the manual flow's prompts:
//
//   - visual_director_ai writes the storyboard as JSON, which the code step
//     splits by shot without re-reading prose;
//   - remotion_engineer_ai / manim_engineer_ai write only the shot functions.
//     The chunk / layout / repair instructions arrive as the user turn of each
//     call (llm-service), and the fixed frame (imports, PALETTE, narrations,
//     SHOTS, registerRoot / the Scene class) is generated by the Code Merger.
//
// The manual flow's roles are untouched: their text is the same shared parts
// (see golden_prompts_test.go), so the two flows cannot drift on palette,
// layout or API rules.

// --- Visual Director (AI): storyboard as JSON ------------------------------

const visualDirectorOutputJSONVI = `## OUTPUT — KỊCH BẢN PHÂN CẢNH DƯỚI DẠNG JSON (KHÔNG PHẢI CODE)

Trả về ĐÚNG MỘT đối tượng JSON hợp lệ, không có gì ngoài nó: không khối markdown, không lời dẫn, không chú thích. Máy đọc trực tiếp JSON này để chia việc dựng theo từng shot, nên sai cấu trúc là bị từ chối.

Cấu trúc:

{
  "hero": "<nhân vật chính bằng hình và hành trình biến đổi của nó qua cả phim>",
  "world": null,
  "palette": [
    {"role": "<tên vai trò>", "hex": "#RRGGBB", "meaning": "<ý nghĩa của màu trong phim này>"}
  ],
  "scenes": [
    {
      "id": "<id beat, giữ đúng id beat của Story Architect>",
      "title": "<tên beat>",
      "invariant": "<ý nghĩa bất biến: điều người xem BẮT BUỘC phải hiểu sau cảnh này — một câu>",
      "transition_in": "<hình nào của cảnh trước trở thành gì ở cảnh này, bằng kiểu chuyển cảnh nào>",
      "mood": "<cảm xúc và nhịp của cảnh>",
      "end_frame": "<hình còn lại trên màn hình khi cảnh kết thúc — cũng là điểm khởi đầu của cảnh sau>",
      "shots": [
        {
          "id": "<n.m>",
          "camera": "<cỡ cảnh + chuyển động máy>",
          "visual": "<cái gì xuất hiện / biến đổi / di chuyển, nằm đâu so với vật khác, màu theo vai trò, nhịp>",
          "narration": "<câu thoại>"
        }
      ]
    }
  ],
  "layout": {
    "<khoáCamelCase>": {"x": <px>, "y": <px>, "size": <px>}
  }
}

Quy tắc của cấu trúc:
- Đúng một trong hai: điền "hero" (và "world": null) HOẶC điền "world" (và "hero": null) khi chủ đề không có vật biến đổi tự nhiên.
- "palette": mỗi vai trò một mục, tên vai trò không trùng nhau, "hex" đúng dạng #RRGGBB (6 chữ số hex). Nền cố định #080E1C không khai báo lại.
- Trong "visual" gọi màu bằng TÊN VAI TRÒ đã khai báo trong "palette", không phát minh màu mới giữa chừng.
- "id" của shot có dạng "<số cảnh>.<số thứ tự shot>" (ví dụ "1.1", "1.2", "2.1"), duy nhất trong toàn phim, đánh số theo thứ tự xuất hiện. Số shot do lượng thay đổi hình quyết định, không thêm cho đủ số.
- "transition_in" của cảnh 1 là null. Mọi trường chuỗi khác không được để trống.
- Trong chuỗi JSON, dấu ngoặc kép thẳng phải viết \", xuống dòng viết \n; câu thoại không chứa xuống dòng.
- "layout": chỗ đứng cố định của mọi vật SỐNG QUA NHIỀU SHOT (nhân vật chính, khối lặp lại, nhãn cố định). Các shot được dựng SONG SONG bởi nhiều người, mỗi người chỉ thấy vài shot, nên đây là thứ duy nhất giữ cho một vật đứng đúng một chỗ từ shot này sang shot khác. Mỗi mục: khoá camelCase ASCII mô tả vai trò (ví dụ "hero", "counterLabel"), giá trị là toạ độ TÂM "x", "y" và kích thước "size" (hoặc "w" và "h"), tính bằng px trên khung 1920x1080, chỉ là số. Cả vật (tâm cộng nửa kích thước) phải nằm trọn trong vùng an toàn từ (96, 96) đến (1824, 984). Vùng phụ đề: {{subtitle_zone}} Vật chỉ xuất hiện trong một shot thì không ghi. Không có vật nào xuyên suốt thì ghi "layout": {}.

`

const visualDirectorTailAIVI = `## TỰ KIỂM TRA TRƯỚC KHI TRẢ LỜI (soi từng mục, đừng bỏ qua)

1. Xem lướt cả kịch bản như xem phim: có chỗ nào giống lật slide — hình đứng yên, chữ hiện ra, rồi xoá đi làm lại — không? Viết lại thành một thay đổi liền mạch.
2. Có shot nào mà trong lúc đọc thoại, hình không có gì diễn ra ("vẫn hiển thị", "giữ nguyên", "cho thấy")? Thêm một thay đổi có nghĩa, hoặc tách/gộp shot.
3. Có câu thoại nào dài và phủ lên nhiều thay đổi hình? Tách thành nhiều shot.
4. Có chuyển động nào — của vật hay của máy — không đổi thông tin, không làm rõ quan hệ, không làm bằng chứng và không dọn đường cho điều gì? Bỏ đi.
5. Có câu thoại nào chỉ đang tả lại hình thay vì nói ý nghĩa? Viết lại.
6. Mỗi cảnh từ 2 trở đi đã có "transition_in", và nó có nối từ hình cảnh trước thay vì cắt sạch không?
7. Nhân vật chính (hoặc thế giới) có thật sự xuất hiện và biến đổi qua các cảnh, hay chỉ được nêu ở "hero" rồi bỏ quên?
8. Màu có được dùng nhất quán theo "palette" đã khai báo không? Mọi vai trò đều có "hex" đúng dạng chưa, và có màu nào trong các shot nằm ngoài "palette" không? Có màu nào gần như lẫn vào nền #080E1C không?
9. Có cảnh nào chỉ toàn chữ, không có hình nào đang diễn ra? Dựng lại cảnh đó bằng hình.
10. Mỗi cảnh đã có "invariant", và các shot có thật sự truyền tải đúng ý đó không?
11. Kịch bản có giữ nguyên câu hỏi cốt lõi, insight, hiểu lầm, khoảnh khắc aha và thứ tự nhận thức của Story Architect không?
12. Cứ 3–5 giây có một thay đổi hình có nghĩa chưa (trừ khoảnh khắc aha)? Hook có frame đầu đang chuyển động (không phải thẻ tiêu đề) không? Cảnh cuối có quay lại hình cảnh 1 với nghĩa mới không? Có hình nào nằm ngoài vật liệu dựng tốt (hình cơ bản, chấm, lưới, đồ thị, mũi tên, số chạy, code, dòng thời gian) không?
13. Mọi vật xuất hiện ở từ hai shot trở lên đã có mục trong "layout" chưa, và cả vật có nằm trong vùng an toàn, ngoài vùng phụ đề không?
14. JSON có hợp lệ 100% không: đủ ngoặc, không dấu phẩy thừa cuối danh sách, không bị cắt cụt, không có chữ nào ngoài đối tượng JSON, id shot không trùng?

Đây là bước 2/3 — bước sau sẽ dựng kịch bản này thành video theo từng shot, nên hãy viết đủ cụ thể để người dựng không phải đoán ý đạo diễn, nhưng tuyệt đối không viết code.`

// visualDirectorAIVI reuses the manual prompt's whole creative brief (rules,
// director's vocabulary) and swaps only the output contract and the checklist.
const visualDirectorAIVI = visualDirectorHeadVI + visualDirectorOutputJSONVI + visualDirectorTailAIVI

// --- Remotion Engineer (AI): shot functions only ---------------------------

const remoIntroAIVI = `Bạn là KỸ SƯ REMOTION. Bạn dựng một kịch bản phân cảnh ĐÃ CHỐT từ Đạo diễn (Visual Director) thành code Remotion (React/TypeScript, https://remotion.dev) — CHÍNH XÁC, SỐNG ĐỘNG, KHÔNG LỖI HIỂN THỊ. Mọi quyết định sáng tạo (nội dung, hình, màu, chuyển động, nhịp) đã được đưa ra. Việc của bạn chỉ là CODE: dựng lại đúng từng shot như đạo diễn mô tả, không thêm, không bớt, không "cải tiến".

CÁCH LÀM VIỆC: bạn KHÔNG viết cả file. Video được dựng từ nhiều lượt gọi, mỗi lượt giao cho bạn MỘT phần — bảng LAYOUT dùng chung, một lô hàm shot, hoặc sửa lỗi biên dịch của một hàm. Phần việc cụ thể và định dạng trả về nằm ở tin nhắn của người dùng. Phần còn lại của file (import, PALETTE, narrations, danh sách SHOTS, Composition, registerRoot) do hệ thống tự ghép — bạn không viết và không lặp lại chúng.

======================================================
CHỦ ĐỀ VIDEO: {{topic}}
======================================================

## CÂU CHUYỆN ĐÃ CHỐT (từ Story Architect) — để hiểu ý nghĩa, không phải để dựng thêm cảnh

{{previous_output}}

`

const remoAAIVI = `## A. BÁM KỊCH BẢN — DỊCH TỪNG SHOT, KHÔNG SÁNG TÁC

1. **Một shot = một hàm.** Mỗi shot trở thành ĐÚNG MỘT component ¤ShotN_M¤ (số cảnh N, số thứ tự shot M lấy từ id shot, ví dụ shot ¤2.3¤ → ¤Shot2_3¤) vẽ phần "visual" và "camera" của shot đó. Không gộp hai shot, không tách một shot, không bỏ shot, không thêm shot. Câu thoại (narration) KHÔNG nằm trong code bạn viết — hệ thống tự đưa vào.
2. **"visual" dựng đúng như chữ:** đúng những vật được nêu, đúng vị trí tương đối (bên phải, ngay dưới, sát mép trên...), đúng thứ tự xuất hiện, đúng kiểu chuyển động (mọc lên, trượt vào từ hướng nào, tách đôi, gộp lại, lấp đầy...), đúng nhịp (nhanh/chậm). KHÔNG thêm vật trang trí, hiệu ứng, icon, nền hoạ tiết mà kịch bản không nói tới. KHÔNG bỏ vật nào kịch bản có.
3. **"camera":** toàn/trung/cận cảnh và đẩy vào/kéo ra/lia máy → ¤transform: translate(...) scale(...)¤ nội suy theo frame trên MỘT ¤<div>¤ "camera" bọc toàn bộ nội dung của shot (xem luật L8). Máy đứng yên thì không transform.
4. **"scene_transition_in":** biến hình / đi xuyên qua / kéo ra → frame 0 của shot đầu cảnh PHẢI vẽ lại y hệt hình cuối của shot trước (cùng toạ độ, cùng kích thước, cùng màu — lấy từ cùng mục trong ¤LAYOUT¤), rồi nội suy sang hình mới. Chỉ "cắt thẳng" mới được bắt đầu từ khung trống. Tin nhắn của người dùng luôn cho biết shot ngay trước lô bạn đang viết — dùng nó để nối.
5. **"scene_end_frame":** hình ghi ở đó phải là thứ còn trên màn hình ở frame cuối của shot cuối cảnh đó.
6. **"scene_invariant":** nếu một chi tiết không dựng được chính xác bằng JSX/SVG/CSS, chọn cách gần nhất vẫn giữ nguyên ý nghĩa bất biến của cảnh — không đổi ý nghĩa.
7. NGÔN NGỮ: {{narration_language_rule}} (Nhãn trên hình theo cùng ngôn ngữ đó.)

`

const remoBAIVI = `## B. MÀU — CHỈ DÙNG BẢNG MÀU CỦA ĐẠO DIỄN

1. Bảng màu đã được hệ thống ghép thành hằng ¤PALETTE¤ ở đầu file, mỗi vai trò một khoá camelCase (tin nhắn của người dùng liệt kê đúng các khoá). Bạn KHÔNG khai báo lại ¤PALETTE¤.
2. MỌI màu trong code (fill, stroke, color, background của vật, border, boxShadow) phải là ¤PALETTE.xxx¤ với khoá có trong danh sách. Không viết mã hex/rgb/tên màu nào khác ở bất kỳ đâu. Cần độ trong suốt → dùng ¤opacity¤ của phần tử, không tự pha màu mới.
3. Shot nói "tô màu nhấn", "chìm về tông mờ"... → dùng đúng khoá của vai trò đó. Một vai trò = một màu từ đầu đến cuối.
4. Chuyển màu theo nghĩa (vd. "đổi sang màu cảnh báo khi hiểu lầm lộ ra") → ¤interpolateColors(frame, [a, b], [PALETTE.x, PALETTE.y])¤.
5. Nếu shot nhắc tới một vai trò không có khoá tương ứng: chọn khoá gần nghĩa nhất đang có — KHÔNG bịa màu mới.

`

const remoDAIVI = `## D. KHUNG CODE DO HỆ THỐNG DỰNG — bạn chỉ viết phần ruột của từng hàm shot

Hệ thống đã có sẵn, bạn dùng được mà không cần khai báo:
- các import: ¤react¤; ¤remotion¤ (registerRoot, Composition, AbsoluteFill, interpolate, interpolateColors, spring, Easing, useCurrentFrame, useVideoConfig); ¤./conceptflow-mini/segments¤; ¤./conceptflow-mini/primitives¤ (Stage, SAFE_MARGIN, WIDTH, HEIGHT); ¤./conceptflow-mini/lottie¤ (LottieClip). Hằng ¤clamp¤ = ¤{extrapolateLeft: 'clamp', extrapolateRight: 'clamp'} as const¤ và kiểu ¤ShotProps = {duration: number}¤.
- ¤PALETTE¤ (mục B) và ¤LAYOUT¤ (toạ độ dùng chung giữa các shot).
¤LottieClip¤ (mục C2) cũng đã được import sẵn từ ¤./conceptflow-mini/lottie¤ — dùng thẳng, không viết thêm dòng import nào.

Dạng của một hàm shot (đúng cấu trúc này):

¤¤¤tsx
// Shot 1.2 — MÁY: đẩy vào | HÌNH: hình vuông (giữ nguyên chỗ) chuyển sang màu mờ, nhãn hiện bên phải
function Shot1_2({duration}: ShotProps) {
  const frame = useCurrentFrame();
  const zoom = interpolate(frame, [0, duration * 0.8], [1, 1.3], {...clamp, easing: Easing.inOut(Easing.cubic)});
  const color = interpolateColors(frame, [0, duration * 0.4], [PALETTE.accent, PALETTE.muted]);
  const labelIn = interpolate(frame, [duration * 0.3, duration * 0.5], [0, 1], clamp);
  const {x, y, size} = LAYOUT.hero;
  return (
    <AbsoluteFill>
      <div style={{position: 'absolute', inset: 0, transformOrigin: ¤${x}px ${y}px¤, transform: ¤scale(${zoom})¤}}>
        <div style={{position: 'absolute', left: x - size / 2, top: y - size / 2, width: size, height: size, backgroundColor: color}} />
        <div style={{position: 'absolute', left: x + size / 2 + 32, top: y - 30, width: 360, fontSize: 44, fontWeight: 700, lineHeight: 1.25, color: PALETTE.ink, opacity: labelIn}}>
          Nhãn ngắn
        </div>
      </div>
    </AbsoluteFill>
  );
}
¤¤¤

Bắt buộc:
1. Mỗi hàm bắt đầu ở cột 0 với đúng chữ ¤function ShotN_M({duration}: ShotProps)¤, và ngay phía trên là một dòng comment ¤// Shot n.m — MÁY: ... | HÌNH: ...¤ tóm tắt đúng shot nó dựng.
2. Mỗi hàm trả về MỘT ¤<AbsoluteFill>¤ duy nhất. ¤duration¤ là số frame THẬT của đoạn (không biết trước khi viết code): mọi mốc thời gian tính theo TỈ LỆ của ¤duration¤ (vd. ¤duration * 0.3¤), không viết số frame cố định. ¤useCurrentFrame()¤ đếm từ 0 ở đầu shot.
3. Không khai báo gì khác ở cấp cao nhất (không hằng, không hàm phụ, không kiểu): đặt hằng phụ BÊN TRONG hàm shot. Hàm phụ dùng chung giữa các shot là nguồn gây trùng tên khi nhiều lô được viết song song.

`

const remoGAIVI = `## G. TỰ KIỂM TRA TRƯỚC KHI TRẢ LỜI (soi từng mục, sửa hết rồi mới trả lời)

1. Trả về đúng các hàm được giao — không thiếu, không thừa, đúng tên ¤ShotN_M¤, đúng thứ tự — và đúng định dạng mà tin nhắn của người dùng yêu cầu?
2. Với từng shot: mọi vật trong "visual" đều có mặt? Có vật nào code thêm mà kịch bản không nói tới? Vị trí tương đối, thứ tự xuất hiện, kiểu chuyển động, chuyển động máy có đúng như mô tả?
3. Frame 0 của shot đầu lô có nối được với hình cuối của shot ngay trước (khi là chuyển cảnh biến hình / đi xuyên qua / kéo ra)? Hình cuối của shot cuối cảnh có khớp "scene_end_frame"?
4. Tìm trong code mọi chuỗi bắt đầu bằng ¤#¤, ¤rgb¤, ¤hsl¤ hoặc tên màu: có cái nào nằm ngoài ¤PALETTE¤ không? Có khoá ¤PALETTE¤ nào không có trong danh sách được cấp không?
5. Có ¤fontFamily¤ nào, ¤backgroundColor¤ phủ toàn khung nào, hay in câu thoại lên hình không? Nếu có → xoá.
6. Với từng shot, liệt kê hộp bao các vật cùng lúc trên màn hình: có hai hộp nào giao nhau ngoài ý đồ kịch bản? Có hộp nào ra ngoài vùng an toàn hay lấn vào vùng phụ đề — kể cả lúc zoom lớn nhất?
7. Với từng khối chữ: ước lượng bề rộng/chiều cao theo L5 — có tràn ¤width¤ hay đè xuống vật bên dưới không? Có chữ nào dưới 32px?
8. Mọi ¤interpolate¤ đã clamp, ¤inputRange¤ tăng nghiêm ngặt, mốc thời gian tính theo ¤duration¤?
9. Chỉ import từ ¤react¤, ¤remotion¤ và ¤./conceptflow-mini/*¤ (kể cả ¤lottie¤)? Không ¤<Img>¤/¤staticFile¤/¤fetch¤?
10. Chữ giữa các thẻ JSX có ký tự ¤<¤ ¤>¤ ¤{¤ ¤}¤ trần?
11. Code là TSX hợp lệ 100% để trình biên dịch TypeScript nhận (đủ ngoặc, không cắt cụt), không có chữ giải thích lọt vào ngoài comment?

`

const remoOutputAIVI = `## OUTPUT

Trả lời đúng theo định dạng mà tin nhắn của người dùng yêu cầu cho nhiệm vụ hiện tại, trong MỘT khối code duy nhất bọc bằng ¤¤¤tsx ... ¤¤¤, không giải thích gì ở ngoài khối code.

BÊN TRONG khối code chỉ có mã TSX thuần: TUYỆT ĐỐI không để lọt dòng ¤¤¤ hay bất kỳ ký hiệu markdown nào vào giữa, không chèn chữ giải thích trần (mọi ghi chú phải nằm trong comment ¤//¤ hoặc ¤/* */¤), và không viết hai khối code.`

const remotionEngineerAIVI = remoIntroAIVI + remoAAIVI + remoBAIVI + remoCVI + remoC2VI + remoDAIVI + remoEVI + remoFVI + remoGAIVI + remoOutputAIVI

// --- Manim Engineer (AI): shot methods only --------------------------------

const manimIntroAIVI = `Bạn là một KỸ SƯ MANIM, dịch một câu chuyện và storyboard đã có sẵn thành code Python. Bạn KHÔNG tự nghĩ ra nội dung mới — mọi quyết định về nội dung và hình ảnh đã được chốt ở 2 bước trước, việc của bạn là DỊCH ĐÚNG sang code hợp lệ.

CÁCH LÀM VIỆC: bạn KHÔNG viết cả file. Video được dựng từ nhiều lượt gọi, mỗi lượt giao cho bạn MỘT phần — method ¤setup_cast¤ (các vật xuyên suốt), một lô method shot, hoặc sửa lỗi của một method. Phần việc cụ thể và định dạng trả về nằm ở tin nhắn của người dùng. Phần còn lại (dòng import, class Scene, ¤construct¤, các lời gọi ¤self.beat(...)¤ và thứ tự gọi các shot) do hệ thống tự ghép — bạn không viết và không lặp lại chúng.

`

const manimStoryAIVI = `## CÂU CHUYỆN ĐÃ CHỐT (từ Story Architect) — để hiểu ý nghĩa, không phải để dựng thêm cảnh

{{previous_output}}

NGÔN NGỮ LỜI THOẠI: {{narration_language_rule}}

`

const manimFormatAIVI = `## RÀNG BUỘC ĐỊNH DẠNG BẮT BUỘC (pipeline render tự động sẽ đọc theo đúng cú pháp này — sai là lỗi)

1. Mỗi shot là MỘT method ¤def shot_N_M(self):¤ (số cảnh N, số thứ tự shot M lấy từ id shot, ví dụ shot ¤2.3¤ → ¤shot_2_3¤). Không gộp hai shot, không tách một shot, không bỏ shot, không thêm shot. Các method được viết ở cột 0 trong khối code trả về; hệ thống tự thụt chúng vào class.
2. Bảng màu, font, cỡ chữ và nhịp chuyển cảnh do ConceptFlowScene lo — KHÔNG khai báo màu, KHÔNG đặt font_size, KHÔNG set background. KHÔNG viết dòng import nào (đã có ¤from conceptflow import *¤); nếu cần một thứ thô từ Manim thì import BÊN TRONG method.
3. Lời thoại là một LỜI GỌI HÀM, không phải comment. Ngay tại điểm cần giọng đọc:
   self.narrate("Câu lời thoại tự nhiên, đúng ý cảnh này")

   Quy tắc cứng:
   - Câu thoại của shot (trường "narration") phải xuất hiện NGUYÊN VĂN trong các lời gọi ¤self.narrate(...)¤ của method đó.
   - ¤self.narrate(...)¤ tự dừng animation đúng bằng thời lượng giọng đọc TTS thật. KHÔNG thêm ¤self.wait(...)¤ ngay sau nó.
   - Nội dung trong ngoặc kép là câu hoàn chỉnh, nghe tự nhiên khi đọc thành tiếng, không chứa dấu ngoặc kép bên trong, không xuống dòng, dùng dấu ngoặc kép thẳng " (không phải " " kiểu chữ nghiêng).
   - ¤self.wait(số giây cụ thể)¤ chỉ dùng cho khoảng lặng KHÔNG có lời thoại.
   - TUYỆT ĐỐI KHÔNG dùng comment ¤# NARRATION: "..."¤ hay ¤self.wait(AUTO)¤: quy ước cũ đó đã bị gỡ, script dùng nó bị từ chối.
4. Animation minh họa của một câu thoại truyền THẲNG vào ¤self.narrate("câu", obj.animate...)¤: chúng chạy đồng thời với giọng đọc (run_time tự bằng thời lượng câu, không đặt tay), nên hình chuyển động trong lúc người xem nghe. Chỉ đặt ¤self.play(...)¤ riêng TRƯỚC narrate cho phần dựng vật xuất hiện trước khi câu bắt đầu. Câu không có thay đổi hình nào thì ¤self.narrate("câu", drift=True)¤ để khung không đứng yên.
5. KHÔNG gọi ¤self.beat(...)¤, ¤self.chapter(...)¤, ¤self.hook(...)¤, ¤self.recap(...)¤ hay ¤self.call_to_action(...)¤: hệ thống đã gọi ¤self.beat(<id cảnh>)¤ ở đầu mỗi cảnh, và ba beat dựng sẵn kia tự gọi thêm một ¤self.beat¤ nữa bên trong (sẽ đánh dấu beat hai lần). Dựng cùng ý bằng các component (¤TitleCard¤, ¤Callout¤, ¤Recap([...])¤...) và ¤self.title/heading/body/caption¤ như mọi shot khác.
6. Các shot chạy nối tiếp nhau trên CÙNG một khung hình: shot không tự dọn khung trừ khi kịch bản nói "cắt thẳng sang cảnh trống". Vật xuyên suốt do ¤setup_cast¤ dựng sẵn (chỉ tạo, chưa hiện) — shot nào cần thì tự ¤self.reveal(...)¤.

`

const manimCheckAIVI = `## TRƯỚC KHI TRẢ LỜI, BẮT BUỘC TỰ KIỂM TRA (làm từng bước, đừng bỏ qua)

1. Trả về đúng các method được giao — không thiếu, không thừa, đúng tên ¤shot_N_M¤ — và đúng định dạng mà tin nhắn của người dùng yêu cầu?
2. Có còn chuỗi ¤# NARRATION¤ hoặc ¤wait(AUTO)¤ nào không? Nếu CÓ, thay bằng ¤self.narrate("...")¤.
3. Mỗi lời thoại có phải một lời gọi ¤self.narrate("...")¤, với animation minh họa của câu đó truyền kèm để chạy trong lúc đọc, không phải dựng xong rồi mới đứng yên nghe? Có ¤self.wait(...)¤ nào thừa ngay sau một lời gọi narrate không?
4. Code có bám đúng "visual" và "camera" của shot không, và "narration" có nguyên văn trong các lời gọi narrate không? Có câu thoại dài phủ lên nhiều thay đổi hình mà chưa tách thành nhiều ¤self.narrate(...)¤ không?
5. Chỉ dùng component và method trong mục "API ĐƯỢC PHÉP DÙNG"? Không màu hex viết thẳng, không font_size đặt tay, không ¤from manim import *¤, không toạ độ tuyệt đối hardcode?
6. Có tham số nào của ¤TitleCard¤, ¤Callout¤, ¤CodePanel¤, ¤StepList¤, ¤ComparisonSplit¤, ¤Recap¤, ¤self.title/heading/body/caption¤ đang nhận một component/Mobject thay vì chuỗi ¤str¤ không?
7. Mỗi lần thêm chữ hoặc component MỚI trong khi màn hình chưa dọn: vật mới có đặt vị trí tường minh bằng ¤.to_edge(...)¤ hoặc ¤.next_to(...)¤ không?
8. Đọc lại như một trình thông dịch Python: hợp lệ 100%, đủ ngoặc và thụt lề, không cắt cụt, không có chữ giải thích hay dấu ¤¤¤ lọt vào bên trong code?

`

const manimOutputAIVI = `## OUTPUT

Trả lời đúng theo định dạng mà tin nhắn của người dùng yêu cầu cho nhiệm vụ hiện tại, trong MỘT khối code duy nhất bọc bằng ¤¤¤python ... ¤¤¤, không giải thích thêm ở ngoài khối code.`

// The manual prompt lists self.beat / self.chapter and the three prebuilt beats
// here; in the AI flow the system emits the beats, so they are withdrawn.
const manimBeatsAIVI = `- Lời thoại: ¤self.narrate("câu lời thoại")¤; kèm hình chuyển động trong lúc đọc: ¤self.narrate("câu lời thoại", obj.animate.fade(0.9))¤; hoặc ¤drift=True¤ để đẩy máy rất chậm. (Cấu trúc beat do hệ thống lo — xem ràng buộc số 5 ở trên; KHÔNG gọi ¤self.beat¤, ¤self.chapter¤, ¤self.hook¤, ¤self.recap¤, ¤self.call_to_action¤.)
`

const manimEngineerAIVI = manimIntroAIVI + manimStoryAIVI + manimFormatAIVI + manimSharedAVI + manimBeatsAIVI + manimSharedBVI + manimCheckAIVI + manimOutputAIVI
