import { useEffect, useRef, useState } from "react";
import {
  ApiError,
  getProjectThumbnailUrl,
  getThumbnailInfo,
  suggestPublishMetadata,
  uploadThumbnail,
} from "../api/client";
import glass from "../styles/glass.module.css";
import styles from "./ThumbnailUpload.module.css";
import { useRenderedPrompt } from "../hooks/useRenderedPrompt";
import { useOperationRun } from "../hooks/useOperationRun";
import { AiOperationCard } from "./AiOperationCard";
import { OperationProgressCard } from "./OperationProgressCard";
import { formatChars } from "../lib/formatProgress";
import { Button, Card, TextArea } from "./ui";

interface ThumbnailUploadProps {
  projectId: string;
  onThumbnailPathChange: (thumbnailPath: string | null) => void;
  /**
   * The project's content language (CR-008 FR21.5). It steers the *topic*
   * wording the prompt is built around; the image prompt itself stays English
   * either way — see THUMBNAIL_SYSTEM_PROMPT's OUTPUT section for why.
   */
  contentLanguage: "vi" | "en";
}

type UploadState = "idle" | "uploading" | "success" | "error";

function WandIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
      <path d="M15 4V2M15 16v-2M8 9h2M20 9h2M17.8 11.8L19 13M17.8 6.2L19 5M12.2 6.2L11 5M12.2 11.8L11 13" />
      <path d="M3 21l9-9M12.2 15.8l4-4" />
    </svg>
  );
}

function CopyIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
      <rect x="9" y="9" width="12" height="12" rx="2" />
      <path d="M5 15H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v1" />
    </svg>
  );
}

export function ThumbnailUpload({
  projectId,
  onThumbnailPathChange,
  contentLanguage,
}: ThumbnailUploadProps) {
  const [topic, setTopic] = useState<string | null>(null);
  const [topicState, setTopicState] = useState<"idle" | "loading" | "error">("idle");
  const topicRun = useOperationRun();
  const { begin: beginTopicRun, end: endTopicRun } = topicRun;
  const [uploadBytes, setUploadBytes] = useState<{ loaded: number; total: number } | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [uploadState, setUploadState] = useState<UploadState>("idle");
  // True while the preview is the frame Video Assembly extracted rather than
  // an image the Creator chose (CR-006 FR16.2) — they should know it is a
  // suggestion they can replace.
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [promptPanelOpen, setPromptPanelOpen] = useState(false);
  const [promptCopied, setPromptCopied] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // CR-040 FR113: rendered by the server from the `thumbnail_design` role. `topic`
  // is the AI-suggested title (the same one the publish form uses), so the copied
  // prompt is already specific to this video. Only rendered while the panel is open.
  const renderedPrompt = useRenderedPrompt(
    promptPanelOpen ? { role: "thumbnail_design", language: contentLanguage, topic: topic ?? "" } : null,
  );
  const thumbnailSystemPrompt = renderedPrompt.prompt ?? (renderedPrompt.failed ? "Không tải được prompt." : "Đang tải prompt...");

  useEffect(() => {
    // Fetched lazily on first open, not on mount — this hits the same
    // AI-suggestion call the publish form's "Gợi ý AI" button makes, so it
    // shouldn't fire before the Creator actually wants a prompt.
    if (!promptPanelOpen || topic !== null || topicState === "loading") return;
    let cancelled = false;
    setTopicState("loading");
    suggestPublishMetadata(projectId, beginTopicRun())
      .then((suggestion) => {
        if (cancelled) return;
        endTopicRun();
        setTopic(suggestion.title ?? null);
        setTopicState("idle");
      })
      .catch(() => {
        if (cancelled) return;
        setTopicState("error");
      });
    return () => {
      cancelled = true;
    };
  }, [promptPanelOpen, projectId, topic, topicState, beginTopicRun, endTopicRun]);

  useEffect(() => {
    let cancelled = false;
    getThumbnailInfo(projectId)
      .then((info) => {
        if (cancelled || !info.exists) return;
        setPreviewUrl(`${getProjectThumbnailUrl(projectId)}?t=${Date.now()}`);
        setIsAutoGenerated(Boolean(info.auto_generated));
        onThumbnailPathChange(info.thumbnail_path);
      })
      .catch(() => {
        /* no existing thumbnail — leave state as idle */
      });
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectId]);

  async function handleFileSelected(event: React.ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file) return;

    // Clear previous error when user tries new upload
    setErrorMessage(null);
    setUploadState("uploading");
    setUploadBytes(null);
    setPreviewUrl(URL.createObjectURL(file));

    try {
      const result = await uploadThumbnail(projectId, file, (loaded, total) => setUploadBytes({ loaded, total }));
      setUploadState("success");
      setIsAutoGenerated(false);
      onThumbnailPathChange(result.thumbnail_path);
    } catch (err) {
      setUploadState("error");
      setErrorMessage(err instanceof ApiError ? err.message : String(err));
      onThumbnailPathChange(null);
    }
  }

  async function handleCopyPrompt() {
    try {
      await navigator.clipboard.writeText(thumbnailSystemPrompt);
      setPromptCopied(true);
      setTimeout(() => setPromptCopied(false), 2000);
    } catch {
      setPromptCopied(false);
    }
  }

  return (
    <Card className={styles.wrapper}>
      <div className={styles.header}>
        <div className={styles.label}>Thumbnail</div>
        <Button
          variant="ghost"
          data-testid="thumbnail-system-prompt-toggle"
          onClick={() => setPromptPanelOpen((open) => !open)}
        >
          <WandIcon />
          Prompt tạo thumbnail
        </Button>
      </div>

      {promptPanelOpen && (
        <div className={styles.promptPanel} data-testid="thumbnail-system-prompt-panel">
          <div className={styles.promptPanelHeader}>
            <span>Prompt để nhờ AI tạo thumbnail (Midjourney, DALL-E…)</span>
            <Button variant="ghost" disabled={topicState === "loading" || renderedPrompt.prompt === null || renderedPrompt.stale} onClick={handleCopyPrompt}>
              <CopyIcon />
              {promptCopied ? "Đã sao chép" : "Sao chÃ©p"}
            </Button>
          </div>
          <AiOperationCard
            run={topicRun}
            active={topicState === "loading"}
            testId="thumbnail-topic-progress"
            title="Đang lấy chủ đề video"
          />
          {topicState === "error" && (
            <p role="alert" className={glass.helperText} style={{ marginTop: 0, fontSize: 12 }}>
              Chưa lấy được chủ đề video. Hãy dán chủ đề vào prompt bên dưới.
            </p>
          )}
          <TextArea
            className={styles.promptTextarea}
            data-testid="thumbnail-system-prompt-textarea"
            value={thumbnailSystemPrompt}
            readOnly
            rows={10}
          />
        </div>
      )}

      <div className={styles.row}>
        {previewUrl ? (
          <div>
            <img src={previewUrl} alt="Thumbnail preview" className={styles.preview} />
            {isAutoGenerated && (
              <p
                className={glass.helperText}
                style={{ marginRight: 0, marginTop: 6, fontSize: 12 }}
                data-testid="thumbnail-auto-generated-note"
              >
                Ảnh gợi ý được lấy từ video. Thumbnail thiết kế riêng thường thu hút nhiều lượt xem hơn.
              </p>
            )}
          </div>
        ) : (
          <div className={styles.placeholder}>Chưa có thumbnail</div>
        )}

        <button
          type="button"
          data-testid="thumbnail-upload-button"
          className={styles.uploadBtn}
          disabled={uploadState === "uploading"}
          onClick={() => fileInputRef.current?.click()}
        >
          {uploadState === "uploading" ? "Đang tải lên..." : "Tải ảnh lên"}
        </button>
        <input
          ref={fileInputRef}
          type="file"
          accept="image/jpeg,image/png"
          data-testid="thumbnail-file-input"
          className={styles.hiddenInput}
          onChange={handleFileSelected}
        />
      </div>

      {/* Never replaces the preview/button above — success or error is
          appended as its own element at the end, so the existing UI stays
          intact after an upload attempt. */}
      {uploadState === "uploading" && uploadBytes && (
        <OperationProgressCard
          testId="thumbnail-upload-progress"
          subtitle={`Đang tải lên · ${formatChars(uploadBytes.loaded)}/${formatChars(uploadBytes.total)}`}
          done={uploadBytes.loaded}
          total={uploadBytes.total}
        />
      )}
      {uploadState === "success" && (
        <span data-testid="thumbnail-upload-success" className={styles.successBadge}>
          ✓ Đã tải lên thành công
        </span>
      )}
      {uploadState === "error" && (
        <span role="alert" data-testid="thumbnail-upload-error" className={styles.errorBadge}>
          {errorMessage}
        </span>
      )}
    </Card>
  );
}
